// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKtiBINXs0UH90qxyQQus-Ow_NHPyzlno',
    appId: '1:461728840541:web:c7311b6d299df338fd86b4',
    messagingSenderId: '461728840541',
    projectId: 'area51cando',
    authDomain: 'area51cando.firebaseapp.com',
    storageBucket: 'area51cando.appspot.com',
    measurementId: 'G-80QB7QQZW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHeYyk8Q7DOO88nc-l0egfL3KbrBFrXx8',
    appId: '1:461728840541:android:c9055930cdd76315fd86b4',
    messagingSenderId: '461728840541',
    projectId: 'area51cando',
    storageBucket: 'area51cando.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNP9BmN-lclL9qzu-8zaiz1v2hEBPKw1c',
    appId: '1:461728840541:ios:2d67ffaedaba30c4fd86b4',
    messagingSenderId: '461728840541',
    projectId: 'area51cando',
    storageBucket: 'area51cando.appspot.com',
    iosClientId: '461728840541-176v374k0gnj7aem8bl3ue0vl67rcr39.apps.googleusercontent.com',
    iosBundleId: 'com.example.area51',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNP9BmN-lclL9qzu-8zaiz1v2hEBPKw1c',
    appId: '1:461728840541:ios:2d67ffaedaba30c4fd86b4',
    messagingSenderId: '461728840541',
    projectId: 'area51cando',
    storageBucket: 'area51cando.appspot.com',
    iosClientId: '461728840541-176v374k0gnj7aem8bl3ue0vl67rcr39.apps.googleusercontent.com',
    iosBundleId: 'com.example.area51',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKtiBINXs0UH90qxyQQus-Ow_NHPyzlno',
    appId: '1:461728840541:web:88307e079f0b9bc5fd86b4',
    messagingSenderId: '461728840541',
    projectId: 'area51cando',
    authDomain: 'area51cando.firebaseapp.com',
    storageBucket: 'area51cando.appspot.com',
    measurementId: 'G-XCRXJVFWMS',
  );

}